In [56]:
#import libraries
import pandas as pd
import matplotlib as plt
import numpy as np
import requests
from bs4 import BeautifulSoup

In [57]:
# Choose the year, read api keys file and assign variables
census_api_key = "663083891f5b9346c0f75af604c1bb8f7e48712b"
YEAR = 2015

In [58]:
#Create function that can convert json data to dataframe
def json_to_dataframe(response):
    """
    Convert response to dataframe
    """
    return pd.DataFrame(response.json()[1:], columns=response.json()[0])

In [59]:
#Create Variables for different racies
varT= "B17001_004E,B17001_005E,B17001_006E,B17001_007E,B17001_008E,B17001_009E,B17001_010E,B17001_011E,B17001_012E,B17001_013E,B17001_014E,B17001_015E,B17001_016E,B17001_018E,B17001_019E,B17001_020E,B17001_021E,B17001_022E,B17001_023E,B17001_024E,B17001_025E,B17001_026E,B17001_027E,B17001_028E,B17001_029E,B17001_030E"
varA= "B17001A_004E,B17001A_005E,B17001A_006E,B17001A_007E,B17001A_008E,B17001A_009E,B17001A_010E,B17001A_011E,B17001A_012E,B17001A_013E,B17001A_014E,B17001A_015E,B17001A_016E,B17001A_018E,B17001A_019E,B17001A_020E,B17001A_021E,B17001A_022E,B17001A_023E,B17001A_024E,B17001A_025E,B17001A_026E,B17001A_027E,B17001A_028E,B17001A_029E,B17001A_030E"
varB= "B17001B_004E,B17001B_005E,B17001B_006E,B17001B_007E,B17001B_008E,B17001B_009E,B17001B_010E,B17001B_011E,B17001B_012E,B17001B_013E,B17001B_014E,B17001B_015E,B17001B_016E,B17001B_018E,B17001B_019E,B17001B_020E,B17001B_021E,B17001B_022E,B17001B_023E,B17001B_024E,B17001B_025E,B17001B_026E,B17001B_027E,B17001B_028E,B17001B_029E,B17001B_030E"
varC= "B17001C_004E,B17001C_005E,B17001C_006E,B17001C_007E,B17001C_008E,B17001C_009E,B17001C_010E,B17001C_011E,B17001C_012E,B17001C_013E,B17001C_014E,B17001C_015E,B17001C_016E,B17001C_018E,B17001C_019E,B17001C_020E,B17001C_021E,B17001C_022E,B17001C_023E,B17001C_024E,B17001C_025E,B17001C_026E,B17001C_027E,B17001C_028E,B17001C_029E,B17001C_030E"
varD= "B17001D_004E,B17001D_005E,B17001D_006E,B17001D_007E,B17001D_008E,B17001D_009E,B17001D_010E,B17001D_011E,B17001D_012E,B17001D_013E,B17001D_014E,B17001D_015E,B17001D_016E,B17001D_018E,B17001D_019E,B17001D_020E,B17001D_021E,B17001D_022E,B17001D_023E,B17001D_024E,B17001D_025E,B17001D_026E,B17001D_027E,B17001D_028E,B17001D_029E,B17001D_030E"
varE= "B17001E_004E,B17001E_005E,B17001E_006E,B17001E_007E,B17001E_008E,B17001E_009E,B17001E_010E,B17001E_011E,B17001E_012E,B17001E_013E,B17001E_014E,B17001E_015E,B17001E_016E,B17001E_018E,B17001E_019E,B17001E_020E,B17001E_021E,B17001E_022E,B17001E_023E,B17001E_024E,B17001E_025E,B17001E_026E,B17001E_027E,B17001E_028E,B17001E_029E,B17001E_030E"
varF= "B17001F_004E,B17001F_005E,B17001F_006E,B17001F_007E,B17001F_008E,B17001F_009E,B17001F_010E,B17001F_011E,B17001F_012E,B17001F_013E,B17001F_014E,B17001F_015E,B17001F_016E,B17001F_018E,B17001F_019E,B17001F_020E,B17001F_021E,B17001F_022E,B17001F_023E,B17001F_024E,B17001F_025E,B17001F_026E,B17001F_027E,B17001F_028E,B17001F_029E,B17001F_030E"
varG= "B17001G_004E,B17001G_005E,B17001G_006E,B17001G_007E,B17001G_008E,B17001G_009E,B17001G_010E,B17001G_011E,B17001G_012E,B17001G_013E,B17001G_014E,B17001G_015E,B17001G_016E,B17001G_018E,B17001G_019E,B17001G_020E,B17001G_021E,B17001G_022E,B17001G_023E,B17001G_024E,B17001G_025E,B17001G_026E,B17001G_027E,B17001G_028E,B17001G_029E,B17001G_030E"
varH= "B17001H_004E,B17001H_005E,B17001H_006E,B17001H_007E,B17001H_008E,B17001H_009E,B17001H_010E,B17001H_011E,B17001H_012E,B17001H_013E,B17001H_014E,B17001H_015E,B17001H_016E,B17001H_018E,B17001H_019E,B17001H_020E,B17001H_021E,B17001H_022E,B17001H_023E,B17001H_024E,B17001H_025E,B17001H_026E,B17001H_027E,B17001H_028E,B17001H_029E,B17001H_030E"
varI= "B17001I_004E,B17001I_005E,B17001I_006E,B17001I_007E,B17001I_008E,B17001I_009E,B17001I_010E,B17001I_011E,B17001I_012E,B17001I_013E,B17001I_014E,B17001I_015E,B17001I_016E,B17001I_018E,B17001I_019E,B17001I_020E,B17001I_021E,B17001I_022E,B17001I_023E,B17001I_024E,B17001I_025E,B17001I_026E,B17001I_027E,B17001I_028E,B17001I_029E,B17001I_030E"

#Name of the variables above
name= ["Male less than 5","Male 5","Male 6-11","Male 12-14","Male 15","Male 16-17","Male 18-24","Male 25-34","Male 35-44","Male 45-54","Male 55-64","Male 65-74","Male 75 and older", "Female less than 5","Female 5","Female 6-11","Female 12-14","Female 15","Female 16-17","Female 18-24","Female 25-34","Female 35-44", "Female 45-54", "Female 55-64","Female 65-74","Female 75 and older"]

In [60]:
#Detailed age data
#Get the API Data for each variables. (Poverty in Jefferson county by race)
urlT = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=county:111&in=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varT)
urlA = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=county:111&in=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varA)
urlB = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=county:111&in=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varB)
urlC = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=county:111&in=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varC)
urlD = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=county:111&in=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varD)
urlE = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=county:111&in=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varE)
urlF = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=county:111&in=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varF)
urlG = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=county:111&in=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varG)
urlH = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=county:111&in=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varH)
urlI = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=county:111&in=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varI)

#Transfer the json data to dataframe
DFT = json_to_dataframe(requests.request("GET", urlT))
DFA = json_to_dataframe(requests.request("GET", urlA))
DFB = json_to_dataframe(requests.request("GET", urlB))
DFC = json_to_dataframe(requests.request("GET", urlC))
DFD = json_to_dataframe(requests.request("GET", urlD))
DFE = json_to_dataframe(requests.request("GET", urlE))
DFF = json_to_dataframe(requests.request("GET", urlF))
DFG = json_to_dataframe(requests.request("GET", urlG))
DFH = json_to_dataframe(requests.request("GET", urlH))
DFI = json_to_dataframe(requests.request("GET", urlI))

#Add additional info for the race
DFT['info'] = "Total poverty population"
DFA['info'] = "White Alone"
DFB['info'] = "Black or African American Alone"
DFC['info'] = "American Indian and Alaska Native Alone"
DFD['info'] = "Asian Alone"
DFE['info'] = "Native Hawaiian ana Other Pacific Islander Alone"
DFF['info'] = "Some Other Race Alone"
DFG['info'] = "Two or More Races"
DFH['info'] = "White Alone, Not Hispanic or Latino"
DFI['info'] = "Hispanic or Latino"

#Concate the dataframes into one dataframe
dfageJ = pd.DataFrame(np.concatenate([DFT.values, DFA.values, DFB.values,DFC.values, DFD.values,
                                  DFE.values,DFF.values, DFG.values, DFH.values,DFI.values]))

#Add column name
dfageJ.columns = ["Location", "Male less than 5","Male 5","Male 6-11","Male 12-14","Male 15","Male 16-17","Male 18-24","Male 25-34","Male 35-44","Male 45-54","Male 55-64","Male 65-74","Male 75 and older", "Female less than 5","Female 5","Female 6-11","Female 12-14","Female 15","Female 16-17","Female 18-24","Female 25-34","Female 35-44", "Female 45-54", "Female 55-64","Female 65-74","Female 75 and older","State code","County code","info"]

In [62]:
'''
#Add new measures by combine columns
dfageJ["Male under 18"]= dfageJ[["Male less than 5","Male 5","Male 6-11","Male 12-14","Male 15","Male 16-17"]].sum(axis =1, skipna=True)
dfageJ["Female under 18"]= dfageJ[["Female less than 5","Female 5","Female 6-11","Female 12-14","Female 15","Female 16-17"]].sum(axis =1, skipna=True)
dfageJ["Male Above 64"]= dfageJ[["Male 65-74","Male 75 and older"]].sum(axis =1, skipna=True)
dfageJ["Female Above 64"]= dfageJ[["Female 65-74","Female 75 and older"]].sum(axis =1, skipna=True)
dfageJ["Male 18-64"]= dfageJ[["Male 18-24","Male 25-34","Male 35-44","Male 45-54","Male 55-64"]].sum(axis =1, skipna=True)
dfageJ["Female 18-64"]= dfageJ[["Female 18-24","Female 25-34","Female 35-44", "Female 45-54", "Female 55-64"]].sum(axis =1, skipna=True)
'''

#Drop the State code column.
dfageJ = dfageJ.drop(["State code","County code"], axis=1)

dfageJ

,Location,Male less than 5,Male 5,Male 6-11,Male 12-14,Male 15,Male 16-17,Male 18-24,Male 25-34,Male 35-44,...,Female 15,Female 16-17,Female 18-24,Female 25-34,Female 35-44,Female 45-54,Female 55-64,Female 65-74,Female 75 and older,info
0,"Jefferson County, Kentucky",6290,978,5695,3474,878,2040,5073,6234,5328,...,1480,1990,8537,10223,7020,6192,4991,3368,3560,Total poverty population
1,"Jefferson County, Kentucky",2494,716,1421,1257,16,666,3016,4332,3730,...,446,854,4496,5587,3658,3940,2699,2194,2422,White Alone
2,"Jefferson County, Kentucky",2908,150,3515,2038,862,1145,2057,1638,1570,...,822,971,3279,4346,3123,2209,2266,1128,1112,Black or African American Alone
3,"Jefferson County, Kentucky",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,American Indian and Alaska Native Alone
4,"Jefferson County, Kentucky",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,Asian Alone
5,"Jefferson County, Kentucky",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,Native Hawaiian ana Other Pacific Islander Alone
6,"Jefferson County, Kentucky",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,Some Other Race Alone
7,"Jefferson County, Kentucky",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,Two or More Races
8,"Jefferson County, Kentucky",1918,445,1394,1128,16,635,2421,3926,3348,...,311,791,4177,5167,3473,3602,2578,2164,2266,"White Alone, Not Hispanic or Latino"
9,"Jefferson County, Kentucky",602,271,104,129,0,94,678,488,410,...,135,63,465,438,236,438,147,30,156,Hispanic or Latino

In [63]:
#Detailed age data for the state of KY
#Get the API Data for each variables. 
urlT = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varT)
urlA = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varA)
urlB = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varB)
urlC = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varC)
urlD = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varD)
urlE = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varE)
urlF = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varF)
urlG = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varG)
urlH = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varH)
urlI = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=state:21&key={1}"\
    .format(YEAR,census_api_key,A=varI)

#Transfer the json data to dataframe
DFT = json_to_dataframe(requests.request("GET", urlT))
DFA = json_to_dataframe(requests.request("GET", urlA))
DFB = json_to_dataframe(requests.request("GET", urlB))
DFC = json_to_dataframe(requests.request("GET", urlC))
DFD = json_to_dataframe(requests.request("GET", urlD))
DFE = json_to_dataframe(requests.request("GET", urlE))
DFF = json_to_dataframe(requests.request("GET", urlF))
DFG = json_to_dataframe(requests.request("GET", urlG))
DFH = json_to_dataframe(requests.request("GET", urlH))
DFI = json_to_dataframe(requests.request("GET", urlI))

#Add additional info for the race
DFT['info'] = "Total poverty population"
DFA['info'] = "White Alone"
DFB['info'] = "Black or African American Alone"
DFC['info'] = "American Indian and Alaska Native Alone"
DFD['info'] = "Asian Alone"
DFE['info'] = "Native Hawaiian ana Other Pacific Islander Alone"
DFF['info'] = "Some Other Race Alone"
DFG['info'] = "Two or More Races"
DFH['info'] = "White Alone, Not Hispanic or Latino"
DFI['info'] = "Hispanic or Latino"

#Concate the dataframes into one dataframe
dfageK = pd.DataFrame(np.concatenate([DFT.values, DFA.values, DFB.values,DFC.values, DFD.values,
                                  DFE.values,DFF.values, DFG.values, DFH.values,DFI.values]))

#Add column name
dfageK.columns = ["Location", "Male less than 5","Male 5","Male 6-11","Male 12-14","Male 15","Male 16-17","Male 18-24","Male 25-34","Male 35-44","Male 45-54","Male 55-64","Male 65-74","Male 75 and older", "Female less than 5","Female 5","Female 6-11","Female 12-14","Female 15","Female 16-17","Female 18-24","Female 25-34","Female 35-44", "Female 45-54", "Female 55-64","Female 65-74","Female 75 and older","State code","info"]

In [64]:
'''
#Add new measures by combine columns
dfageK["Male under 18"]= dfageK[["Male less than 5","Male 5","Male 6-11","Male 12-14","Male 15","Male 16-17"]].sum(axis =1, skipna=True)
dfageK["Female under 18"]= dfageK[["Female less than 5","Female 5","Female 6-11","Female 12-14","Female 15","Female 16-17"]].sum(axis =1, skipna=True)
dfageK["Male Above 64"]= dfageK[["Male 65-74","Male 75 and older"]].sum(axis =1, skipna=True)
dfageK["Female Above 64"]= dfageK[["Female 65-74","Female 75 and older"]].sum(axis =1, skipna=True)
dfageK["Male 18-64"]= dfageK[["Male 18-24","Male 25-34","Male 35-44","Male 45-54","Male 55-64"]].sum(axis =1, skipna=True)
dfageK["Female 18-64"]= dfageK[["Female 18-24","Female 25-34","Female 35-44", "Female 45-54", "Female 55-64"]].sum(axis =1, skipna=True)
'''

#Drop the State code column.
dfageK = dfageK.drop(["State code"], axis=1)

dfageK

,Location,Male less than 5,Male 5,Male 6-11,Male 12-14,Male 15,Male 16-17,Male 18-24,Male 25-34,Male 35-44,...,Female 15,Female 16-17,Female 18-24,Female 25-34,Female 35-44,Female 45-54,Female 55-64,Female 65-74,Female 75 and older,info
0,Kentucky,40132,8050,41551,19835,6500,11307,44669,41222,37807,...,8591,13082,59435,65972,51920,50067,39319,24809,23034,Total poverty population
1,Kentucky,29860,5964,29850,14679,4382,8468,36770,34515,32191,...,6619,10442,47780,54621,44265,43941,33270,21558,20294,White Alone
2,Kentucky,6015,946,7558,2735,1737,1861,5615,4246,3645,...,1260,1813,7727,8514,5540,5131,5096,2696,2592,Black or African American Alone
3,Kentucky,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,American Indian and Alaska Native Alone
4,Kentucky,175,0,399,52,0,34,228,735,559,...,149,139,1060,852,781,154,100,81,0,Asian Alone
5,Kentucky,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,Native Hawaiian ana Other Pacific Islander Alone
6,Kentucky,1212,389,695,644,66,315,705,562,567,...,107,185,489,720,949,14,26,46,0,Some Other Race Alone
7,Kentucky,2846,751,3049,1255,315,463,1300,1020,707,...,456,503,2237,1197,248,691,524,354,148,Two or More Races
8,Kentucky,28066,4891,28431,14179,4095,8173,35212,32898,30542,...,5899,9852,45967,52261,42627,43136,33040,21372,19847,"White Alone, Not Hispanic or Latino"
9,Kentucky,3144,1379,2287,1492,443,804,2397,2557,2335,...,844,803,2524,3062,2601,905,305,186,447,Hispanic or Latino

In [65]:
#Detailed age data for the US
#Get the API Data for each variables. 
urlT = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=us:*&key={1}"\
    .format(YEAR,census_api_key,A=varT)
urlA = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=us:*&key={1}"\
    .format(YEAR,census_api_key,A=varA)
urlB = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=us:*&key={1}"\
    .format(YEAR,census_api_key,A=varB)
urlC = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=us:*&key={1}"\
    .format(YEAR,census_api_key,A=varC)
urlD = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=us:*&key={1}"\
    .format(YEAR,census_api_key,A=varD)
urlE = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=us:*&key={1}"\
    .format(YEAR,census_api_key,A=varE)
urlF = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=us:*&key={1}"\
    .format(YEAR,census_api_key,A=varF)
urlG = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=us:*&key={1}"\
    .format(YEAR,census_api_key,A=varG)
urlH = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=us:*&key={1}"\
    .format(YEAR,census_api_key,A=varH)
urlI = "https://api.census.gov/data/{0}/acs/acs1?get=NAME,{A}&for=us:*&key={1}"\
    .format(YEAR,census_api_key,A=varI)

#Transfer the json data to dataframe
DFT = json_to_dataframe(requests.request("GET", urlT))
DFA = json_to_dataframe(requests.request("GET", urlA))
DFB = json_to_dataframe(requests.request("GET", urlB))
DFC = json_to_dataframe(requests.request("GET", urlC))
DFD = json_to_dataframe(requests.request("GET", urlD))
DFE = json_to_dataframe(requests.request("GET", urlE))
DFF = json_to_dataframe(requests.request("GET", urlF))
DFG = json_to_dataframe(requests.request("GET", urlG))
DFH = json_to_dataframe(requests.request("GET", urlH))
DFI = json_to_dataframe(requests.request("GET", urlI))

#Add additional info for the race
DFT['info'] = "Total poverty population"
DFA['info'] = "White Alone"
DFB['info'] = "Black or African American Alone"
DFC['info'] = "American Indian and Alaska Native Alone"
DFD['info'] = "Asian Alone"
DFE['info'] = "Native Hawaiian ana Other Pacific Islander Alone"
DFF['info'] = "Some Other Race Alone"
DFG['info'] = "Two or More Races"
DFH['info'] = "White Alone, Not Hispanic or Latino"
DFI['info'] = "Hispanic or Latino"

#Concate the dataframes into one dataframe
dfageUS = pd.DataFrame(np.concatenate([DFT.values, DFA.values, DFB.values,DFC.values, DFD.values,
                                  DFE.values,DFF.values, DFG.values, DFH.values,DFI.values]))

#Add column name
dfageUS.columns = ["Location", "Male less than 5","Male 5","Male 6-11","Male 12-14","Male 15","Male 16-17","Male 18-24","Male 25-34","Male 35-44","Male 45-54","Male 55-64","Male 65-74","Male 75 and older", "Female less than 5","Female 5","Female 6-11","Female 12-14","Female 15","Female 16-17","Female 18-24","Female 25-34","Female 35-44", "Female 45-54", "Female 55-64","Female 65-74","Female 75 and older","US","info"]

In [66]:
'''
#Add new measures by combine columns
dfageUS["Male under 18"]= dfageUS[["Male less than 5","Male 5","Male 6-11","Male 12-14","Male 15","Male 16-17"]].sum(axis =1, skipna=True)
dfageUS["Female under 18"]= dfageUS[["Female less than 5","Female 5","Female 6-11","Female 12-14","Female 15","Female 16-17"]].sum(axis =1, skipna=True)
dfageUS["Male Above 64"]= dfageUS[["Male 65-74","Male 75 and older"]].sum(axis =1, skipna=True)
dfageUS["Female Above 64"]= dfageUS[["Female 65-74","Female 75 and older"]].sum(axis =1, skipna=True)
dfageUS["Male 18-64"]= dfageUS[["Male 18-24","Male 25-34","Male 35-44","Male 45-54","Male 55-64"]].sum(axis =1, skipna=True)
dfageUS["Female 18-64"]= dfageUS[["Female 18-24","Female 25-34","Female 35-44", "Female 45-54", "Female 55-64"]].sum(axis =1, skipna=True)
'''
#Drop the State code column.
dfageUS = dfageUS.drop(["US"], axis=1)

dfageUS

,Location,Male less than 5,Male 5,Male 6-11,Male 12-14,Male 15,Male 16-17,Male 18-24,Male 25-34,Male 35-44,...,Female 15,Female 16-17,Female 18-24,Female 25-34,Female 35-44,Female 45-54,Female 55-64,Female 65-74,Female 75 and older,info
0,United States,2249826,455160,2631142,1150989,390150,728066,2960657,2494283,2016312,...,381805,725825,3621707,3879329,3019798,2549636,2380221,1360028,1348011,Total poverty population
1,United States,1217648,250979,1447505,629083,217944,398248,1864569,1532864,1263960,...,204721,399036,2285998,2320285,1804943,1603142,1555112,926050,997260,White Alone
2,United States,552041,111747,634450,288571,95386,178615,519369,472659,372157,...,98554,185749,688124,874625,657457,552779,521324,252621,204473,Black or African American Alone
3,United States,35677,6073,41148,17003,5436,12896,35081,39776,31431,...,5776,11360,49457,55280,41228,42347,36359,15738,10200,American Indian and Alaska Native Alone
4,United States,55654,12616,66081,33670,12234,30251,223977,152673,87680,...,14011,26510,214311,174534,130758,112169,102741,78290,73345,Asian Alone
5,United States,5889,1537,4309,2509,1393,1830,6661,6270,3775,...,1006,2063,9238,11617,6069,5475,3820,2445,1385,Native Hawaiian ana Other Pacific Islander Alone
6,United States,219138,43598,270698,112501,37478,68224,197036,212372,206633,...,37297,68689,234242,322524,300268,170674,112447,62396,45194,Some Other Race Alone
7,United States,163779,28610,166951,67652,20279,38002,113964,77669,50676,...,20440,32418,140337,120464,79075,63050,48418,22488,16154,Two or More Races
8,United States,698080,137924,803949,358110,131885,245047,1458839,1119133,854865,...,123045,246131,1777616,1639639,1203004,1265761,1307267,766958,862280,"White Alone, Not Hispanic or Latino"
9,United States,815101,167908,994328,415376,130680,241226,645256,659716,641873,...,128458,236295,793994,1066531,946289,532608,382829,234969,189521,Hispanic or Latino

In [67]:
#Join the three tables
dfageMerge = pd.concat([dfageJ, dfageK, dfageUS])

#Add Year 
dfageMerge["Year"]=YEAR

#Export it as csv
dfageMerge.to_csv('Poverty_Age.csv')

In [68]:
#dfageMerge

,Location,Male less than 5,Male 5,Male 6-11,Male 12-14,Male 15,Male 16-17,Male 18-24,Male 25-34,Male 35-44,...,Female 16-17,Female 18-24,Female 25-34,Female 35-44,Female 45-54,Female 55-64,Female 65-74,Female 75 and older,info,Year
0,"Jefferson County, Kentucky",6290,978,5695,3474,878,2040,5073,6234,5328,...,1990,8537,10223,7020,6192,4991,3368,3560,Total poverty population,2015
1,"Jefferson County, Kentucky",2494,716,1421,1257,16,666,3016,4332,3730,...,854,4496,5587,3658,3940,2699,2194,2422,White Alone,2015
2,"Jefferson County, Kentucky",2908,150,3515,2038,862,1145,2057,1638,1570,...,971,3279,4346,3123,2209,2266,1128,1112,Black or African American Alone,2015
3,"Jefferson County, Kentucky",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,American Indian and Alaska Native Alone,2015
4,"Jefferson County, Kentucky",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,Asian Alone,2015
5,"Jefferson County, Kentucky",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,Native Hawaiian ana Other Pacific Islander Alone,2015
6,"Jefferson County, Kentucky",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,Some Other Race Alone,2015
7,"Jefferson County, Kentucky",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,Two or More Races,2015
8,"Jefferson County, Kentucky",1918,445,1394,1128,16,635,2421,3926,3348,...,791,4177,5167,3473,3602,2578,2164,2266,"White Alone, Not Hispanic or Latino",2015
9,"Jefferson County, Kentucky",602,271,104,129,0,94,678,488,410,...,63,465,438,236,438,147,30,156,Hispanic or Latino,2015
0,Kentucky,40132,8050,41551,19835,6500,11307,44669,41222,37807,...,13082,59435,65972,51920,50067,39319,24809,23034,Total poverty population,2015
1,Kentucky,29860,5964,29850,14679,4382,8468,36770,34515,32191,...,10442,47780,54621,44265,43941,33270,21558,20294,White Alone,2015
2,Kentucky,6015,946,7558,2735,1737,1861,5615,4246,3645,...,1813,7727,8514,5540,5131,5096,2696,2592,Black or African American Alone,2015
3,Kentucky,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,American Indian and Alaska Native Alone,2015
4,Kentucky,175,0,399,52,0,34,228,735,559,...,139,1060,852,781,154,100,81,0,Asian Alone,2015
5,Kentucky,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,Native Hawaiian ana Other Pacific Islander Alone,2015
6,Kentucky,1212,389,695,644,66,315,705,562,567,...,185,489,720,949,14,26,46,0,Some Other Race Alone,2015
7,Kentucky,2846,751,3049,1255,315,463,1300,1020,707,...,503,2237,1197,248,691,524,354,148,Two or More Races,2015
8,Kentucky,28066,4891,28431,14179,4095,8173,35212,32898,30542,...,9852,45967,52261,42627,43136,33040,21372,19847,"White Alone, Not Hispanic or Latino",2015
9,Kentucky,3144,1379,2287,1492,443,804,2397,2557,2335,...,803,2524,3062,2601,905,305,186,447,Hispanic or Latino,2015
0,United States,2249826,455160,2631142,1150989,390150,728066,2960657,2494283,2016312,...,725825,3621707,3879329,3019798,2549636,2380221,1360028,1348011,Total poverty population,2015
1,United States,1217648,250979,1447505,629083,217944,398248,1864569,1532864,1263960,...,399036,2285998,2320285,1804943,1603142,1555112,926050,997260,White Alone,2015
2,United States,552041,111747,634450,288571,95386,178615,519369,472659,372157,...,185749,688124,874625,657457,552779,521324,252621,204473,Black or African American Alone,2015
3,United States,35677,6073,41148,17003,5436,12896,35081,39776,31431,...,11360,49457,55280,41228,42347,36359,15738,10200,American Indian and Alaska Native Alone,2015
4,United States,55654,12616,66081,33670,12234,30251,223977,152673,87680,...,26510,214311,174534,130758,112169,102741,78290,73345,Asian Alone,2015
5,United States,5889,1537,4309,2509,1393,1830,6661,6270,3775,...,2063,9238,11617,6069,5475,3820,2445,1385,Native Hawaiian ana Other Pacific Islander Alone,2015
6,United States,219138,43598,270698,112501,37478,68224,197036,212372,206633,...,68689,234242,322524,300268,170674,112447,62396,45194,Some Other Race Alone,2015
7,United States,163779,28610,166951,67652,20279,38002,113964,77669,50676,...,32418,140337,120464,79075,63050,48418,22488,16154,Two or More Races,2015
8,United States,698080,137924,803949,358110,131885,245047,1458839,1119133,854865,...,246131,1777616,1639639,1203004,1265761,1307267,766958,862280,"White Alone, Not Hispanic or Latino",2015
9,United States,815101,167908,994328,415376,130680,241226,645256,659716,641873,...,236295,793994,1066531,946289,532608,382829,234969,189521,Hispanic or Latino,2015